version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "NuGet"
          command: nuget.exe restore EVEMon.sln
      - run:
          name: "Build Application according to some given configuration"
          command: msbuild -t:build -restore -p:BclBuildImported=Ignore  -p:Configuration=Release EVEMon.sln 
      - store_artifacts:
          path: src\EVEMon\bin\Installbuilder\Installer\
          destination: Installer
workflows:
  test_and_build:
    jobs:
      - build
